In [1]:
import pandas as pd

# Membaca dataset dari folder dataset_raw
df = pd.read_csv('../dataset_raw/dataset_dummy.csv')
display(df)

   id  umur  nilai_ujian  status_lulus
0   1  21.0         85.0             1
1   2  22.0          NaN             0
2   3  20.0         90.0             1
3   4  21.0         75.0             1
4   5   NaN         60.0             0
5   6  23.0         88.0             1
6   7  20.0         45.0             0
7   8  22.0         95.0             1

In [2]:
print("--- Info Dataset ---")
df.info()

print("\n--- Jumlah Missing Values ---")
print(df.isnull().sum())

--- Info Dataset ---
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            8 non-null      int64
 1   umur          7 non-null      float64
 2   nilai_ujian   7 non-null      float64
 3   status_lulus  8 non-null      int64
dtypes: float64(2), int64(2)
memory usage: 388.0 bytes

--- Jumlah Missing Values ---
id              0
umur            1
nilai_ujian     1
status_lulus    0
dtype: int64

In [3]:
# Menghapus baris yang memiliki missing values (nilai kosong)
df_clean = df.dropna()

print("--- Dataset setelah dibersihkan ---")
display(df_clean)

--- Dataset setelah dibersihkan ---

   id  umur  nilai_ujian  status_lulus
0   1  21.0         85.0             1
2   3  20.0         90.0             1
3   4  21.0         75.0             1
5   6  23.0         88.0             1
6   7  20.0         45.0             0
7   8  22.0         95.0             1